---
abstract: "Add 'xx' dumper to debugger"
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-Pluggable-Dumper
provides:
  DB::Pluggable::Dumper:
    file: lib/DB/Pluggable/Dumper.pm
    version: 0.01
requires:
  DB::Pluggable: 1.100851
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Ovid/DB-Pluggable-Dumper
version: 0.01
